server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: api-user #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-user   #匹配后提供服务的路由地址
          filters:
            - StripPrefix=1
          predicates:
            - Path=/api-user/**   #断言,路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

