server:
  port: 8086
spring:
  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  thymeleaf:
    cache: false
    prefix: classpath:/templates/admin/ # html页面文件
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    enabled: true
    servlet:
      content-type: text/html
  application:
    name: cloud-nacos
  cloud:
    nacos:
      discovery: #Nacos注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport: #dashboard地址
        dashboard: localhost:18080
        port: 18080  #默认端口
      eager: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seate?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
mybatis-plus:
  mapper-locations:  classpath:mapper/*.xml
  typeEnumsPackage: com.wing.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

service-url:
  nacos-user-service: http://nacos-provider
feign:
  sentinel:
    enabled: true